### PR TITLE
Aniseed updates and usage improvements

### LINKED ISSUE #9: Aniseed not found
I am getting this error with the latest neovim compiled version:

```^Ino field package.preload['aniseed.core']
^Ino file './aniseed/core.lua'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/share/luajit-2.1.0-beta3/aniseed/core.lua'
^Ino file '/usr/local/share/lua/5.1/aniseed/core.lua'
^Ino file '/usr/local/share/lua/5.1/aniseed/core/init.lua'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/share/lua/5.1/aniseed/core.lua'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/share/lua/5.1/aniseed/core/init.lua'
^Ino file './aniseed/core.so'
^Ino file '/usr/local/lib/lua/5.1/aniseed/core.so'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/lib/lua/5.1/aniseed/core.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file './aniseed.so'
^Ino file '/usr/local/lib/lua/5.1/aniseed.so'
^Ino file '/home/mte90/Desktop/kde/neovim/.deps/usr/lib/lua/5.1/aniseed.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
.../plugged/nvim-tree-docs/lua/nvim-tree-docs/collector.lua:31: attempt to index local '_local_0_' (a nil value)
Failed to load:  /home/mte90/.config/nvim/lua/plugin/ts.lua
^I ...m/plugged/nvim-tree-docs/lua/nvim-tree-docs/internal.lua:31: attempt to index local '_local_0_' (a nil value)```

### PR DESCRIPTION
**Pull request by Olical**
Hi there! I noticed there were a couple of open issues around requiring Aniseed installed as a top level plugin for this plugin to work. That's not intended since Aniseed bundles itself in your Lua output, so you can use the exact version of Aniseed you compiled with at runtime. This PR addresses the following:

 * Update Aniseed and rebulid with the latest code and features.
 * Ensure we refer to `nvim-tree-docs.aniseed.core` instead of `aniseed.core` (which is missing unless you have Aniseed installed explicitly).
 * Use `autoload` over `require` which is a new-ish feature that defers requiring of modules until they're accessed. This has simplified a little bit of the code that was trying to lazily load a module.
 * Use `def-` in a couple of places where a `(local ...)` was used.
 * Move a few `(local ... (require ...))` calls into the `(module ...)` form as well as convert to the lazy autoload.

I've tried this out myself and it still generated documentation in a `.js` file for me, so I think everything's okay? This should fix #9 and #3 which are the same issue as well as potentially speed up loading of the plugin, or at least defer processing until it's invoked by the user.

I hope this is useful, let me know if you have any questions or would like anything addressed!

### CODE REVIEW

**Comment by Mte90** [comment]
any updates for this?

**Comment by Olical** [comment]
The PR hasn't existed for very long at all, please give the maintainers much more time to respond. In the mean time I recommend using my fork if you need this update then switching back if it's eventually merged.

https://github.com/Olical/nvim-tree-docs

**Comment by vigoux** [comment]
I'll let @steelsojka review this one as I am not really into fennel and sure about how this plugin works.

**Comment by steelsojka** [comment]
Sorry... been extremely busy. This looks good to me 👍

**Comment by Olical** [comment]
Nice! Thanks 😄 also if you update Aniseed and recompile your Lua will shrink dramatically. I rewrote and improved a LOT of the underlying module system a while back and I think before I opened this PR.

Not essential, but just a heads up!

**Pull request merged**
